// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Banner.tsx";
import * as $$$$$$1 from "./sections/BlogPosts.tsx";
import * as $$$$$$2 from "./sections/CheckoutSection.tsx";
import * as $$$$$$3 from "./sections/ContentCourse.tsx";
import * as $$$$$$4 from "./sections/ContentSelector.tsx";
import * as $$$$$$5 from "./sections/Faq.tsx";
import * as $$$$$$6 from "./sections/Footer.tsx";
import * as $$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$20 from "./sections/hero-1.tsx";
import * as $$$$$$21 from "./sections/hero-2.tsx";
import * as $$$$$$8 from "./sections/Hero.tsx";
import * as $$$$$$22 from "./sections/hero2.tsx";
import * as $$$$$$9 from "./sections/HtmxHeader.tsx";
import * as $$$$$$10 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$11 from "./sections/LoginSection.tsx";
import * as $$$$$$12 from "./sections/Logos.tsx";
import * as $$$$$$13 from "./sections/PriceCard.tsx";
import * as $$$$$$14 from "./sections/ProductInfo.tsx";
import * as $$$$$$15 from "./sections/RegistrarSecstion.tsx";
import * as $$$$$$16 from "./sections/SummarySection.tsx";
import * as $$$$$$17 from "./sections/Testimonials.tsx";
import * as $$$$$$18 from "./sections/Theme/Theme.tsx";
import * as $$$$$$19 from "./sections/UserPerfil.tsx";
import * as $$$$$$23 from "./sections/ytTestimonial.tsx";

const manifest = {
  "sections": {
    "site/sections/Banner.tsx": $$$$$$0,
    "site/sections/BlogPosts.tsx": $$$$$$1,
    "site/sections/CheckoutSection.tsx": $$$$$$2,
    "site/sections/ContentCourse.tsx": $$$$$$3,
    "site/sections/ContentSelector.tsx": $$$$$$4,
    "site/sections/Faq.tsx": $$$$$$5,
    "site/sections/Footer.tsx": $$$$$$6,
    "site/sections/Header.tsx": $$$$$$7,
    "site/sections/hero-1.tsx": $$$$$$20,
    "site/sections/hero-2.tsx": $$$$$$21,
    "site/sections/Hero.tsx": $$$$$$8,
    "site/sections/hero2.tsx": $$$$$$22,
    "site/sections/HtmxHeader.tsx": $$$$$$9,
    "site/sections/ImageWithParagraph.tsx": $$$$$$10,
    "site/sections/LoginSection.tsx": $$$$$$11,
    "site/sections/Logos.tsx": $$$$$$12,
    "site/sections/PriceCard.tsx": $$$$$$13,
    "site/sections/ProductInfo.tsx": $$$$$$14,
    "site/sections/RegistrarSecstion.tsx": $$$$$$15,
    "site/sections/SummarySection.tsx": $$$$$$16,
    "site/sections/Testimonials.tsx": $$$$$$17,
    "site/sections/Theme/Theme.tsx": $$$$$$18,
    "site/sections/UserPerfil.tsx": $$$$$$19,
    "site/sections/ytTestimonial.tsx": $$$$$$23,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
